---
- name: "Create /etc/sysctl.d/99-illumio.conf"
  file:
    path: /etc/sysctl.d/99-illumio.conf
    state: touch

- name: "Load nf_conntrack module"
  command: modprobe nf_conntrack

- name: "Set OS kernel parameters"
  blockinfile:
    dest: /etc/sysctl.d/99-illumio.conf
    block: |
      fs.file-max          = 2000000
      net.core.somaxconn   = 16384
      net.nf_conntrack_max = 1048576

- name: "Apply the OS kernel settings"
  command: sysctl -p /etc/sysctl.d/99-illumio.conf

- name: "Get current nf_conntrack hashsize"
  shell: "cat /sys/module/nf_conntrack/parameters/hashsize"
  register: nf_conntrack_hashsize
  changed_when: false
  check_mode: no

- name: "Set nf_conntrack hashsize to 262144"
  shell: "echo 262144 > /sys/module/nf_conntrack/parameters/hashsize"
  when: "nf_conntrack_hashsize.stdout != '262144'"

- name: "Create /etc/modprobe.d/illumio.conf"
  file:
    path: /etc/modprobe.d/illumio.conf
    state: touch

- name: "Apply the hash size settings in module"
  blockinfile:
    dest: /etc/modprobe.d/illumio.conf
    block: |
      options nf_conntrack hashsize=262144
