---
- name: "Copy PCE RPM - '{{ pce_rpm_software }}' to /tmp"
  copy:
    src: ../../files/{{ pce_rpm_software }}
    dest: /tmp
  when: pce_rpm_software != ''

- name: "Stopped PCE Cluster"
  command: sudo -u ilo-pce illumio-pce-ctl stop
  register: pce_status
  failed_when: pce_status.rc != 0
