---
- name: "Create /etc/sysctl.d/99-illumio.conf"
  file:
    path: /etc/sysctl.d/99-illumio.conf
    state: touch

- name: "Set OS kernel parameters"
  blockinfile:
    dest: /etc/sysctl.d/99-illumio.conf
    block: |
      fs.file-max          = 2000000
      kernel.shmmax        = 60000000
      vm.overcommit_memory = 1

- name: "Apply the settings"
  command: sysctl -p /etc/sysctl.d/99-illumio.conf
