---
- name: "Create /etc/systemd/system/illumio-pce.service.d/override.conf"
  file:
    path: /etc/systemd/system/illumio-pce.service.d/override.conf
    state: touch

- name: "Set systemd limits"
  blockinfile:
    dest: /etc/systemd/system/illumio-pce.service.d/override.conf
    block: |
      [Service]
      LimitCORE=0
      LimitNOFILE=65535
      LimitNPROC=65535
