---
- name: "Backup PCE DB to {{ backup_directory }}"
  command: sudo -u ilo-pce illumio-pce-db-management dump --file {{ backup_directory }}/backup-{{ ansible_date_time.iso8601_basic_short }}.tgz
  register: backup_status
  failed_when: backup_status.rc != 0
