---
- block:
    - name: "Stopping PCE"
      command: sudo -u ilo-pce illumio-pce-ctl stop

    - name: "Waiting for PCE to stop"
      command: sudo -u ilo-pce illumio-pce-ctl status -w 180
      register: pce_status
      until: pce_status.rc == 0
      retries: 0
  become: true

- block:
    - name: "Uninstall the UI RPM"
      yum:
        name: illumio-pce-ui
        state: absent

    - name: "Uninstall the PCE RPM"
      yum:
        name: illumio-pce
        state: absent
  when: pce_status.rc == 0

- name: "Clean up directories"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/illumio-pce/
    - /var/log/illumio-pce/
    - /etc/illumio-pce
    - /opt/illumio-pce
